name: Issue to File

on:
  issues:
    types: [opened, edited]
  workflow_dispatch:
    inputs:
      path:
        description: 'Path to write (e.g. 02_Work_In_Progress/background_loop_prototype.md)'
        required: true
      content:
        description: 'File content (raw UTF-8)'
        required: true

permissions:
  contents: write
  issues: read

jobs:
  write:
    runs-on: ubuntu-latest
    steps:
      - name: Guard (skip unless proper trigger)
        if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'issues' && startsWith(github.event.issue.title, 'push:')) }}
        run: echo "Triggered correctly"

      - name: Create or update file (from ISSUE)
        if: ${{ github.event_name == 'issues' && startsWith(github.event.issue.title, 'push:') }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const title = context.payload.issue.title || '';
            const path = title.replace(/^push:\s*/i, '').trim();
            const body = context.payload.issue.body || '';
            if (!path) { core.setFailed('No path in issue title'); return; }
            if (!body) { core.setFailed('Issue body is empty'); return; }

            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const content = Buffer.from(body, 'utf8').toString('base64');

            let sha;
            try {
              const res = await github.rest.repos.getContent({ owner, repo, path });
              if (!Array.isArray(res.data)) sha = res.data.sha;
            } catch (e) {
              if (e.status !== 404) throw e;
            }

            await github.rest.repos.createOrUpdateFileContents({
              owner, repo, path,
              message: `chore: update via issue -> ${path}`,
              content,
              sha,
              committer: { name: 'Fuwae Bot', email: 'bot@example.com' },
              author: { name: 'Fuwae Bot', email: 'bot@example.com' }
            });

      - name: Create or update file (from DISPATCH)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const path = core.getInput('path');
            const contentRaw = core.getInput('content');
            if (!path) { core.setFailed('No path'); return; }
            if (!contentRaw) { core.setFailed('No content'); return; }

            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const content = Buffer.from(contentRaw, 'utf8').to
